language: node_js
node_js:
  - "8.11.3"
branches:
  only:
  - master
# cache:
#   directories:
#     - node_modules
# deploy:
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master
# install:
#   - npm install
# script:
#   - npm run test
