language: node_js
node_js:
  - "8.11.3"
branches:
  only:
  - master
install:
  - npm install -g codecov
jobs:
  include:
    - stage: test
      script: npm run test:coverage
    - stage: coverage
      script: - codecov
    - stage: build
      script: npm run build
