language: node_js
node_js:
  - "8.11.3"
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
install:
  - npm i
script:
  - npm run test
  - npm run build