language: node_js
node_js:
  - "8.11.3"
cache:
  directories:
    - node_modules
deploy:
  github_token: $GITHUB_TOKEN
  on:
    branch: master
before_deploy:
  - gem install mime-types -v 2.6.2
install:
  - npm install
script:
  - npm run test
